language: haskell

sudo: false

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin
  - export PATH=/opt/ghc/7.8.4/bin:$PATH

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.8.4

script:
  - stack --no-terminal --skip-ghc-check install hlint
  - stack --no-terminal --skip-ghc-check build
  - stack --no-terminal test
  - hlint src

cache:
  directories:
    - $HOME/.stack
